In [1]:
import numpy as np
import pandas as ps
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [2]:
#wine_data = ps.read_csv("C:\\Users\\p.kovalenko\\Documents\\GitHub\\coursera_ML_tutorial\\coursera_ML_tutorial\\wine.data")
wine_data = ps.read_csv("C:\\Users\\asus\\Desktop\\coursera_ML_tutorial\\wine.data")

In [3]:
print(wine_data)

     Class  Alcohol  Malic_acid   Ash  Alcalinity_of_ash  Magnesium  \
0        1    14.23        1.71  2.43               15.6        127   
1        1    13.20        1.78  2.14               11.2        100   
2        1    13.16        2.36  2.67               18.6        101   
3        1    14.37        1.95  2.50               16.8        113   
4        1    13.24        2.59  2.87               21.0        118   
5        1    14.20        1.76  2.45               15.2        112   
6        1    14.39        1.87  2.45               14.6         96   
7        1    14.06        2.15  2.61               17.6        121   
8        1    14.83        1.64  2.17               14.0         97   
9        1    13.86        1.35  2.27               16.0         98   
10       1    14.10        2.16  2.30               18.0        105   
11       1    14.12        1.48  2.32               16.8         95   
12       1    13.75        1.73  2.41               16.0         89   
13    

In [13]:
#my_cols = set(wine_data.columns)
#print(my_cols)
#matrix_cols = my_cols.remove("Class")
variable_matrix = wine_data.drop(["Class"], axis = 1)
aim_column = list(wine_data["Class"])
#print(variable_matrix)
print(aim_column)
#print(list(aim_column))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [17]:
#cross_validator = KFold(n_splits=5, shuffle=True)
cross_validator = KFold(n_splits=5, shuffle=True, random_state=42)
for train_index, test_index in cross_validator.split(variable_matrix):
    print("TRAIN:", train_index, " TEST:", test_index)

TRAIN: [  0   1   2   3   4   5   6   7   8  10  11  13  14  17  20  21  22  23
  25  26  27  28  32  33  34  35  36  37  38  39  40  43  44  46  47  48
  49  50  51  52  53  54  56  57  58  59  61  62  63  64  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  83  84  85  86  87  88  89  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 110
 112 115 116 120 121 122 123 124 125 126 127 129 130 131 132 133 134 135
 136 137 138 139 142 143 144 146 147 148 149 151 152 153 154 155 156 157
 158 159 160 161 162 163 165 166 167 168 170 172 173 175 176 177]  TEST: [  9  12  15  16  18  19  24  29  30  31  41  42  45  55  60  65  66  67
  82  90 109 111 113 114 117 118 119 128 140 141 145 150 164 169 171 174]
TRAIN: [  0   1   3   5   7   8   9  10  12  13  14  15  16  17  18  19  20  21
  23  24  25  28  29  30  31  33  34  35  37  39  40  41  42  43  44  45
  46  47  48  49  50  52  53  54  55  57  58  59  60  61  62  63  64  65
  66  67  70  71  72  73  74  75  77

In [18]:
k_classifier = KNeighborsClassifier(n_neighbors=7)
print(cross_val_score(k_classifier, variable_matrix, aim_column, cv=cross_validator, scoring="accuracy"))

[0.69444444 0.58333333 0.72222222 0.68571429 0.71428571]


In [23]:
max_accuracy = 0
max_index = 0
for k in range(1,51):
    print(str(k))
    cur_classifier = KNeighborsClassifier(n_neighbors=k)
    cur_accuracy_array = cross_val_score(cur_classifier, variable_matrix, aim_column, cv=cross_validator, scoring="accuracy")
    print(cur_accuracy_array)
    cur_avg_acc = sum(cur_accuracy_array) / len(cur_accuracy_array)
    print(cur_avg_acc)
    if cur_avg_acc > max_accuracy:
        max_accuracy = cur_avg_acc
        max_index = k
print("Max accuracy:", max_accuracy)
print("Max index:", max_index)

1
[0.77777778 0.66666667 0.72222222 0.71428571 0.77142857]
0.7304761904761905
2
[0.72222222 0.63888889 0.69444444 0.57142857 0.68571429]
0.6625396825396825
3
[0.80555556 0.61111111 0.63888889 0.65714286 0.82857143]
0.7082539682539682
4
[0.75       0.52777778 0.61111111 0.65714286 0.74285714]
0.6577777777777778
5
[0.72222222 0.61111111 0.61111111 0.68571429 0.74285714]
0.6746031746031746
6
[0.72222222 0.63888889 0.63888889 0.68571429 0.68571429]
0.6742857142857144
7
[0.69444444 0.58333333 0.72222222 0.68571429 0.71428571]
0.68
8
[0.72222222 0.61111111 0.66666667 0.65714286 0.74285714]
0.6799999999999999
9
[0.72222222 0.63888889 0.72222222 0.68571429 0.74285714]
0.7023809523809523
10
[0.72222222 0.61111111 0.63888889 0.68571429 0.74285714]
0.6801587301587302
11
[0.75       0.63888889 0.66666667 0.71428571 0.74285714]
0.7025396825396826
12
[0.72222222 0.66666667 0.69444444 0.68571429 0.71428571]
0.6966666666666667
13
[0.72222222 0.69444444 0.66666667 0.65714286 0.71428571]
0.6909523809523