In [21]:
import numpy as np
import pandas as ps
import sklearn
import sklearn.model_selection
import sklearn.neighbors
print(sklearn.__version__)

0.21.2


In [12]:
boston_ds = sklearn.datasets.load_boston()

In [13]:
print(boston_ds.data)
boston_data_scaled = sklearn.preprocessing.scale(boston_ds.data)
print(boston_data_scaled)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[[-0.41978194  0.28482986 -1.2879095  ... -1.45900038  0.44105193
  -1.0755623 ]
 [-0.41733926 -0.48772236 -0.59338101 ... -0.30309415  0.44105193
  -0.49243937]
 [-0.41734159 -0.48772236 -0.59338101 ... -0.30309415  0.39642699
  -1.2087274 ]
 ...
 [-0.41344658 -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.98304761]
 [-0.40776407 -0.48772236  0.11573841 ...  1.17646583  0.4032249
  -0.86530163]
 [-0.41500016 -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.66905833]]


In [5]:
print(boston_ds.target)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [15]:
linespaces = np.linspace(1, 10, 200)
print(linespaces)

[ 1.          1.04522613  1.09045226  1.13567839  1.18090452  1.22613065
  1.27135678  1.31658291  1.36180905  1.40703518  1.45226131  1.49748744
  1.54271357  1.5879397   1.63316583  1.67839196  1.72361809  1.76884422
  1.81407035  1.85929648  1.90452261  1.94974874  1.99497487  2.04020101
  2.08542714  2.13065327  2.1758794   2.22110553  2.26633166  2.31155779
  2.35678392  2.40201005  2.44723618  2.49246231  2.53768844  2.58291457
  2.6281407   2.67336683  2.71859296  2.7638191   2.80904523  2.85427136
  2.89949749  2.94472362  2.98994975  3.03517588  3.08040201  3.12562814
  3.17085427  3.2160804   3.26130653  3.30653266  3.35175879  3.39698492
  3.44221106  3.48743719  3.53266332  3.57788945  3.62311558  3.66834171
  3.71356784  3.75879397  3.8040201   3.84924623  3.89447236  3.93969849
  3.98492462  4.03015075  4.07537688  4.12060302  4.16582915  4.21105528
  4.25628141  4.30150754  4.34673367  4.3919598   4.43718593  4.48241206
  4.52763819  4.57286432  4.61809045  4.66331658  4

In [25]:
cross_validator = sklearn.model_selection.KFold(n_splits=5, shuffle=True, random_state=42)
max_sq_error = -10000000000000
min_p = -1
for cur_p in linespaces:
    print(str(cur_p))
    cur_regressor = sklearn.neighbors.KNeighborsRegressor(n_neighbors=5, weights='distance', metric='minkowski', p=cur_p)
    cur_sq_error = sklearn.model_selection.cross_val_score(cur_regressor, boston_data_scaled, boston_ds.target, cv=cross_validator, scoring="neg_mean_squared_error")
    print(cur_sq_error)
    cur_avg_error = sum(cur_sq_error) / len(cur_sq_error)
    print(cur_avg_error)
    if cur_avg_error > max_sq_error:
        max_sq_error = cur_avg_error
        min_p = cur_p
print("Minimum error:", max_sq_error)
print("P of minimum error:", min_p)

1.0
[-20.21899107 -12.49567191 -17.22129105 -11.83373336 -18.38354627]
-16.030646734221644
1.0452261306532664
[-20.22607648 -12.57429075 -17.43647464 -12.07494178 -19.72740989]
-16.40783870832999
1.0904522613065326
[-20.13329413 -12.65479751 -17.68764499 -11.92277511 -19.45497299]
-16.370696947059045
1.135678391959799
[-20.20518452 -12.96135285 -17.65835017 -11.91533174 -19.48836227]
-16.445716308439433
1.1809045226130652
[-19.93196196 -12.90136373 -18.02078301 -11.95450061 -19.56667956]
-16.475057773399403
1.2261306532663316
[-19.80364184 -12.87447015 -17.93740291 -12.11406897 -19.90257779]
-16.526432329318258
1.271356783919598
[-19.92462793 -13.24345009 -17.97716386 -12.09748856 -19.94081629]
-16.636709345898257
1.3165829145728645
[-19.85066747 -13.80890388 -17.68416088 -12.66957076 -20.10781828]
-16.82422425426731
1.3618090452261307
[-19.87699063 -13.94042247 -17.88657538 -12.68019921 -19.98685759]
-16.874209056598744
1.4070351758793969
[-19.86064833 -13.98675631 -19.19762903 -12.65

[-19.15178857 -16.94566396 -21.88504527 -19.68923426 -20.21548573]
-19.577443558088486
4.7537688442211055
[-19.25059484 -16.94481684 -21.98280056 -19.96030832 -20.22610983]
-19.67292607910183
4.798994974874372
[-19.25238905 -16.94863731 -22.04524051 -19.96598558 -20.20894036]
-19.68423856503004
4.844221105527638
[-19.25414986 -17.05918269 -22.12673024 -19.97152241 -20.24551179]
-19.731419398024357
4.889447236180905
[-19.25429529 -16.99742048 -22.135899   -19.97816667 -20.30106408]
-19.73336910414023
4.934673366834171
[-19.25530246 -17.0030907  -22.14143236 -19.98351586 -20.31014024]
-19.738696325445968
4.9798994974874375
[-19.38603187 -17.00864945 -22.14685605 -19.98873549 -20.31966937]
-19.769988446644323
5.025125628140704
[-19.38780425 -16.84710692 -22.07796251 -19.90949373 -20.12932289]
-19.670338059212803
5.07035175879397
[-19.41892321 -16.85712051 -22.08328023 -19.88640317 -20.12584257]
-19.67431393586822
5.115577889447236
[-19.3173279  -16.85728533 -21.92721944 -19.92797021 -20.1

[-20.47244452 -19.55394067 -23.96201188 -20.19235963 -20.86436979]
-21.009025299728833
8.417085427135678
[-20.47277649 -19.55516532 -23.96366767 -20.20248189 -20.86671971]
-21.01216221477924
8.462311557788945
[-20.49151119 -19.55637005 -23.96530003 -20.20331153 -20.86903274]
-21.01710510789645
8.507537688442211
[-20.47548487 -19.55755524 -23.96690941 -20.20412732 -20.87083827]
-21.014983021890455
8.552763819095478
[-20.47579683 -19.55872126 -23.96849621 -20.20492956 -20.8730963 ]
-21.016208031732354
8.597989949748744
[-20.45101492 -19.55986849 -23.97006083 -20.20571853 -20.87531922]
-21.012396399713907
8.64321608040201
[-20.45202774 -19.56099729 -23.97160367 -20.20649452 -20.87404902]
-21.013034449348474
8.688442211055277
[-20.45234378 -19.562108   -23.98335367 -20.20725781 -20.87620674]
-21.016253998579874
8.733668341708544
[-20.44387114 -19.56320098 -24.00026339 -20.14487002 -20.87833116]
-21.006107338225995
8.77889447236181
[-20.4441976  -19.56427656 -24.00177185 -20.14563721 -20.87