In [1]:
import numpy as np

In [4]:
matr = np.random.normal(loc=1,scale=10, size=(100,5))
print(matr)

[[ 5.53068508e+00  1.48849547e+01  1.17885449e+01  5.06973796e+00
  -1.42747760e+01]
 [-1.24431763e+01  2.02186430e+00  1.60850349e+01 -1.91224863e+01
   7.41181755e+00]
 [-8.64058705e+00  3.55856988e+00  1.12252829e+00  1.74295107e+00
   5.50816399e+00]
 [-1.34782331e+00  1.95837588e+01  3.54807337e+00 -7.26235512e-01
   1.90449927e+00]
 [-1.26239213e+00 -4.74054899e+00  6.67641436e+00 -5.49211467e+00
   6.65169192e+00]
 [ 4.64840009e+00  9.27128546e+00  1.60473123e+01  4.73387946e+00
   9.75859521e+00]
 [ 1.93690984e+00  8.62708833e+00 -1.30280639e+01  4.24251407e+00
   1.08996291e+01]
 [-1.08686931e+01  2.24074274e+01  9.30362054e+00  5.12365172e+00
   5.55070179e-01]
 [-6.54280431e+00 -4.34132682e+00  1.69071019e+01  1.17271168e+01
   4.96044169e+00]
 [ 4.78216395e+00 -1.13329893e+00  7.17006737e+00 -1.65970275e+01
   2.43712490e+00]
 [ 5.33428948e+00 -1.00983780e+01  6.49871097e+00 -4.42351788e+00
   1.51283531e+01]
 [ 5.82203351e+00 -5.72254143e-01  4.69521876e+00 -3.70060549e-01

In [8]:
mean = np.mean(matr, axis=0)
print("mean:")
print(mean)
std = np.std(matr, axis=0)
print("std:")
print(std)
matr_norm = ((matr - mean) / std)
print("matr:")
print(matr_norm)

mean:
[0.83547243 1.13214952 2.02110868 0.33417272 2.61562571]
std:
[ 8.93489822  9.8186737   9.55198276  9.60373891 10.07493352]
matr:
[[ 5.25491454e-01  1.40067850e+00  1.02255589e+00  4.93095999e-01
  -1.67647773e+00]
 [-1.48615557e+00  9.06145586e-02  1.47235674e+00 -2.02594627e+00
   4.76051959e-01]
 [-1.06056714e+00  2.47123027e-01 -9.40726567e-02  1.46690613e-01
   2.87102468e-01]
 [-2.44355972e-01  1.87923642e+00  1.59858401e-01 -1.10416187e-01
  -7.05837351e-02]
 [-2.34794455e-01 -5.98115253e-01  4.87365377e-01 -6.06668658e-01
   4.00604748e-01]
 [ 4.26745506e-01  8.28944539e-01  1.46840755e+00  4.58124359e-01
   7.08984281e-01]
 [ 1.23273638e-01  7.63335155e-01 -1.57550249e+00  4.06960391e-01
   8.22239008e-01]
 [-1.30993831e+00  2.16681789e+00  7.62408397e-01  4.98709830e-01
  -2.04522990e-01]
 [-8.25781845e-01 -5.57455774e-01  1.55841919e+00  1.18630298e+00
   2.32737613e-01]
 [ 4.41716450e-01 -2.30728561e-01  5.39046062e-01 -1.76298006e+00
  -1.77173192e-02]
 [ 5.03510722e

In [9]:
sum_strings = np.sum(matr, axis=1)
print("sum_strings")
print(sum_strings)
print("sum more than 20:")
print(np.nonzero(sum_strings > 20))

sum_strings
[ 2.29991467e+01 -6.04694592e+00  3.29162619e+00  2.29622726e+01
  1.83305049e+00  4.44594725e+01  1.26780774e+01  2.65210768e+01
  2.27105293e+01 -3.34097018e+00  1.24394577e+01  1.51380395e+01
  1.92099658e+01 -9.01093837e+00  1.52472708e+01  1.19298569e+01
 -4.60598686e+00  1.01612385e+01 -7.45876217e+00 -2.48889779e+01
  1.80710752e+01  2.57581919e+01  9.48309681e+00  1.43525454e+01
  2.00813434e+01  3.72160930e+01 -3.54968702e+00  1.97001275e+01
  5.11389422e+01  2.86271611e+00 -3.71945361e+00  6.00042958e+00
  4.04373918e+01  3.38225379e+01 -4.73805597e-02  2.09064273e+01
  7.22282848e+00 -2.23282469e+01  3.17643634e+01  1.50488741e+01
  1.54901963e+01  3.63401219e+01 -1.80358880e+01  4.57157759e+00
  1.30903347e+01  3.50752553e+01  4.33357416e+01 -2.25292731e+00
 -4.74444645e+01  3.76734624e+01 -3.90788474e+01  4.08173467e+00
  2.05632259e+01 -1.85246199e+01 -3.80882378e+01 -3.97356753e+00
  2.61898759e+01  1.37716458e+01 -7.79790887e+00  1.53508178e+01
 -2.14059269e

In [10]:
A = np.eye(2)
B = np.eye(2)
print(A)
print(B)
AB = np.vstack((A,B))
print(AB)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]
